In [3]:
# welke partij hoort de spreker bij?
# K-means indelen en kijken of ze in hun eigen groepen zitten
# Veranderen sprekers van visie als ze in de coalitie zitten?
# Maken van een spectrum van sprekers (links/rechts of andere schalen)

import sqlite3
import pandas as pd

db = sqlite3.connect('reports.sqlite')

agenda_items = pd.read_sql_query("SELECT * FROM agenda_items", db)
speaker_items = pd.read_sql_query("SELECT * FROM speaker_turns", db)
speakers = pd.read_sql_query("SELECT * FROM speakers", db)

In [4]:
agenda_items.head()

,id,filename,item_date,agenda_no,title
0,1,h-tk-20162017-59-2.xml,2017-03-23 00:00:00,2,Mededelingen
1,2,h-tk-20162017-59-3.xml,2017-03-23 00:00:00,3,Beëdiging tijdelijke voorzitter
2,3,h-tk-20162017-59-4.xml,2017-03-23 00:00:00,4,Beëdiging leden
3,4,h-tk-20162017-59-5.xml,2017-03-23 00:00:00,5,Vaststelling profielschets nieuwe Voorzitter
4,5,h-tk-20162017-59-6.xml,2017-03-23 00:00:00,6,Regeling van werkzaamheden

In [12]:
speaker_items.head()

,id,agenda_item,turn_no,speaker,txt
0,1,1,1,1,Detijdelijke voorzitter:Ik deel aan de Kamer m...
1,2,5,1,2,Voorzitter. Ik zal het idee van de heer Pechto...
2,3,5,2,2,Zo mogelijk in aanwezigheid van de minister-pr...
3,4,5,3,3,Ik kan mij die behoefte heel goed voorstellen....
4,5,5,4,4,Steun namens D66 voor het verzoek van de heer ...

In [7]:
speakers.head()

   id   prefix        name political
0   1       De  voorzitter      None
1   2  De heer     Omtzigt       CDA
2   3  Mevrouw   Karabulut        SP
3   4  De heer   Verhoeven       D66
4   5  Mevrouw      Kuiken      PvdA